--
-- CONSULTA 1: Calcula o maior intervalo de dias entre a data de entrada e saída nas implantações.
SELECT MAX(DT_SAIDA - DT_ENTRADA) || ' DIAS'
  FROM T_SIP_IMPLANTACAO;

-- CONSULTA 2: Calcula a média salarial por departamento, ordenando do maior para o menor.
SELECT F.CD_DEPTO, D.NM_DEPTO,
       ROUND(AVG(VL_SALARIO_MENSAL),2) "MÉDIA SALARIAL POR DEPTO"
  FROM T_SIP_DEPARTAMENTO D INNER JOIN T_SIP_FUNCIONARIO F
       ON (D.CD_DEPTO = F.CD_DEPTO)
GROUP BY F.CD_DEPTO, D.NM_DEPTO
ORDER BY "MÉDIA SALARIAL POR DEPTO" DESC;

-- CONSULTA 3: Conta o número total de implantações por projeto.
SELECT I.CD_PROJETO, P.NM_PROJETO,
       COUNT (I.CD_IMPLANTACAO) "QTDE.  IMPLANTAÇÕES"
  FROM T_SIP_PROJETO P INNER JOIN T_SIP_IMPLANTACAO I
       ON (P.CD_PROJETO = I.CD_PROJETO)
GROUP BY I.CD_PROJETO, P.NM_PROJETO;

-- CONSULTA 4: Conta o número de implantações em andamento (sem data de saída) por projeto.
SELECT I.CD_PROJETO, P.NM_PROJETO,
       COUNT (I.CD_IMPLANTACAO) "QTDE. IMPLANTAÇÕES EM ANDAMENTO"
  FROM T_SIP_PROJETO P INNER JOIN T_SIP_IMPLANTACAO I
       ON (P.CD_PROJETO = I.CD_PROJETO)
 WHERE I.DT_SAIDA IS NULL
GROUP BY I.CD_PROJETO, P.NM_PROJETO;

-- CONSULTA 5: Conta o número de implantações finalizadas (com data de saída) por projeto.
SELECT I.CD_PROJETO, P.NM_PROJETO,
       COUNT (I.CD_IMPLANTACAO) "QTDE. IMPLANTAÇÕES FINALIZADAS"
  FROM T_SIP_PROJETO P INNER JOIN T_SIP_IMPLANTACAO I
       ON (P.CD_PROJETO = I.CD_PROJETO)
 WHERE I.DT_SAIDA IS NOT NULL
GROUP BY I.CD_PROJETO, P.NM_PROJETO;

-- CONSULTA 6: Conta o número total de implantações realizadas por funcionário.
SELECT I.NR_MATRICULA, F.NM_FUNCIONARIO,
       COUNT (I.CD_IMPLANTACAO) "QTDE.  IMPLANTAÇÕES"
  FROM T_SIP_FUNCIONARIO F INNER JOIN T_SIP_IMPLANTACAO I
       ON (F.NR_MATRICULA = I.NR_MATRICULA)
GROUP BY I.NR_MATRICULA, F.NM_FUNCIONARIO;

