-- Testando DB
SELECT * 
FROM T_SIP_DEPARTAMENTO;

SELECT * 
FROM T_SIP_FUNCIONARIO;

--=================================================
-- Numero de Indexs
SELECT COUNT(*)
FROM T_SIP_DEPARTAMENTO;

-- Não sejam nulos
SELECT COUNT(DT_TERMINO) FROM T_SIP_PROJETO;

SELECT COUNT(CD_PROJETO)
FROM T_SIP_PROJETO
WHERE DT_TERMINO IS NULL;


SELECT *
FROM T_SIP_PROJETO;

-- DISTINCT
SELECT COUNT(DISTINCT cd_projeto)
FROM T_SIP_IMPLANTACAO;

SELECT *
FROM T_SIP_IMPLANTACAO;

-- SUM
SELECT SUM(vl_salario_mensal)
FROM T_SIP_FUNCIONARIO;

SELECT *
FROM T_SIP_FUNCIONARIO;

-- AVG -- AVERAGE
SELECT AVG(vl_salario_mensal)
FROM T_SIP_FUNCIONARIO;


SELECT *
FROM T_SIP_FUNCIONARIO;

-- MIN

SELECT MIN(VL_SALARIO_MENSAL)
FROM T_SIP_FUNCIONARIO;

--MAX

SELECT MAX(VL_SALARIO_MENSAL)
FROM T_SIP_FUNCIONARIO;

-- STD -- DESVIO PADRAO

SELECT STDDEV(VL_SALARIO_MENSAL)
FROM T_SIP_FUNCIONARIO;

-- VARIANCE -- VARIANCIA
SELECT VARIANCE(VL_SALARIO_MENSAL)
FROM T_SIP_FUNCIONARIO;
